# Complete Python NumPy Tutorial 
(Creating Arrays, Indexing, Math, Statistics, Reshaping)

In [2]:
import numpy as np

### The Basics

In [16]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [17]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [18]:
# get diamension
a.ndim

1

In [19]:
# get type
a.dtype

dtype('int32')

In [25]:
# Get size
a.itemsize
b.itemsize

8

In [21]:
# get total size
a.size * a.itemsize

12

In [22]:
# Get shape
a.shape

(3,)

In [23]:
# Get shape
b.shape

(2, 3)

In [24]:
# get total size
a.nbytes

12

### Accessing /Changing specific elements, rows, columns etc..

In [28]:
a =np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [29]:
a.shape

(2, 7)

In [34]:
# Get a specific element [r,c]
# a[1,5]
a[1,-2]

13

In [35]:
# get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [36]:
# get a specific column
a[:,2]

array([ 3, 10])

In [40]:
# Getting a little more fancy [startindex:endindex:stepsize]
# a[0, 1:6:2]                  [1:4:2]
a[0, 1:-1:2]

array([2, 4, 6])

In [46]:
# Replacing the value in the array

# Replacing one element in the array
a[1,5] = 20

# Replacing the element in specific column in the array
a[:,2]= [5]
print(a)

# Replacing the columes in the array
a[:,2]= [1,2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


### *3-d Example

In [47]:
b = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [48]:
# get specific element (work outside in)
b[0,1,1]             # 0-(1st 3d array), 1-(second array in 1st 3d array), 1-(second element in second array under 1st 3d array)

4

In [50]:
# replacing the elements in the 3d array 
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


### Initializing different types of Arrays

In [59]:
# All 0's matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [66]:
# All 1's matrix
np.ones((4,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [68]:
# All other number 
np.full((2,2),99, dtype= 'float32')   # diamentions of (2*2), value = 99

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [70]:
# ANY OTHE NUMBER OTHER LINE 

np.full_like(a,4)

array([4, 4])

In [71]:
# Random decimal number 

np.random.rand(4,2)

array([[0.19234715, 0.52643842],
       [0.0886094 , 0.10044435],
       [0.26759791, 0.32402706],
       [0.49315151, 0.31593264]])

In [72]:
# Random integer value
np.random.randint(-4,8, size=(3,3))

array([[ 0, -2,  7],
       [-2,  3,  7],
       [ 0, -3,  4]])

In [73]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [76]:
# repeat an Array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [98]:
c= np.ones([5,5])
print(c,"\n")

d= np.zeros((3,3))
d[1,1] = 9

print(d,"\n")

c[1:-1,1:-1] =d
print(c)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]] 

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Be catreful while copying arrays !!!

In [104]:
a = np.array([1,2,3])
b= a.copy()
b[1] =100

print(a)
print(b)

[1 2 3]
[  1 100   3]


### Mathematics

In [105]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [106]:
a+2

array([3, 4, 5, 6])

In [107]:
a-2

array([-1,  0,  1,  2])

In [108]:
a*2

array([2, 4, 6, 8])

In [109]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [110]:
b = np.array([1,0,1,0])

a+b

array([2, 2, 4, 4])

In [111]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [112]:
# Take the sin()
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [114]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Linear Algebra

In [120]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [122]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [123]:
### Below value also can be determined...

# Determinant
# trace
# Singular vector decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

#### Statistics

In [124]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
np.min(stats)

1

In [130]:
# (axis = 0) : Row wise maximum value 
np.max(stats, axis=0) 

array([4, 5, 6])

In [132]:
# (axis = 1) : column wise maximum value 
np.max(stats, axis=1) 

array([3, 6])

In [133]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [134]:
np.sum(stats, axis=1)

array([ 6, 15])

### Recoganizing Arrays

In [149]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before,'\n')

after = before.reshape((2,2,2))
print(after)

after = before.reshape((2,3))
print(after)

[[1 2 3 4]
 [5 6 7 8]] 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


ValueError: cannot reshape array of size 8 into shape (2,3)

In [151]:
# Vertically stacking vectors 

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])  # any number of times we can repeat

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [153]:
# Horizontal stacking vectors 

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Mescellaneous
#### load data from file 

In [156]:
filedata = np.genfromtxt("D:\\Data Science\\Dataset\\mescellalenous_data.csv", delimiter = ',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

##### Boolean Masking and Advanced Indexing

In [157]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [158]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [159]:
## you can index with a list in NumPY
a= np.array([1,2,3,4,5,6,7,8,9])

a[[1,2,8]]

array([2, 3, 9])

In [160]:
np.any(filedata >50, axis= 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [161]:
np.all(filedata >50, axis= 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [162]:
np.all(filedata >50, axis= 1)

array([False, False, False])

In [163]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [164]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])