# Data wrangling with  python cheat sheet

#### #1. Creating data frame

In [43]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.DataFrame({
    'a' : [4,5,6],
    'b' : [7,8,9],
    'c' : [10,11,12]
})

In [3]:
df

a  b   c
0  4  7  10
1  5  8  11
2  6  9  12

In [7]:
df1 = pd.DataFrame([[4,5,10],[7,8,20],[10,11,120]], index=[1,2,3], columns=['a','s','d'])

In [8]:
df1

a   s    d
1   4   5   10
2   7   8   20
3  10  11  120

In [9]:
df2 = pd.DataFrame({
    'a' : [4,5,6],
    'b' : [7,8,9],
    'c' : [10,11,12]
}, index = pd.MultiIndex.from_tuples([('d',1),('d',2),('e',2)], names=['n','v']))

In [10]:
df2

a  b   c
n v          
d 1  4  7  10
  2  5  8  11
e 2  6  9  12

In [11]:
pd.melt(df2)

variable  value
0        a      4
1        a      5
2        a      6
3        b      7
4        b      8
5        b      9
6        c     10
7        c     11
8        c     12

In [14]:
df2

a  b   c
n v          
d 1  4  7  10
  2  5  8  11
e 2  6  9  12

In [26]:
pd.concat([df,df1])

0     1      2     a      d     s
0   4.0   5.0   10.0   NaN    NaN   NaN
1   7.0   8.0   20.0   NaN    NaN   NaN
2  10.0  11.0  120.0   NaN    NaN   NaN
1   NaN   NaN    NaN   4.0   10.0   5.0
2   NaN   NaN    NaN   7.0   20.0   8.0
3   NaN   NaN    NaN  10.0  120.0  11.0

In [29]:
pd.concat([df,df1], axis=1)

0     1      2     a     s      d
0   4.0   5.0   10.0   NaN   NaN    NaN
1   7.0   8.0   20.0   4.0   5.0   10.0
2  10.0  11.0  120.0   7.0   8.0   20.0
3   NaN   NaN    NaN  10.0  11.0  120.0

In [23]:
df

0   1    2
0   4   5   10
1   7   8   20
2  10  11  120

In [24]:
df1

a   s    d
1   4   5   10
2   7   8   20
3  10  11  120

In [33]:
df.sample(n=1)

0  1   2
1  7  8  20

In [37]:
df.sample(frac=0.2)

0  1   2
1  7  8  20

In [39]:
df.expanding()

Expanding [min_periods=1,center=False,axis=0]

In [41]:
df.rolling

<bound method NDFrame._add_series_or_dataframe_operations.<locals>.rolling of     0   1    2
0   4   5   10
1   7   8   20
2  10  11  120>

In [44]:
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],
 dtype = float)

In [45]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [48]:
f = np.eye(5)

In [49]:
f

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
 np.linspace(0,2,9) 

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [51]:
e = np.full((2,2),7) 

In [52]:
e

array([[7, 7],
       [7, 7]])

In [53]:
d = np.arange(10,25,5) 

In [54]:
d

array([10, 15, 20])

In [60]:
np.empty((2,3)) 

array([[7.74860419e-304, 7.74860419e-304, 7.74860419e-304],
       [7.74860419e-304, 7.74860419e-304, 7.74860419e-304]])

In [61]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [1]:
import matplotlib.pyplot as plt

In [ ]:
plt.boxplot